config/routes.rb
Rails.application.routes.draw do
  devise_for :users           # no need to set up individual routes if User is the name of model

  #get   '/login',           to: 'login#'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'home#home'# works
  #get   '/locations', to: 'locations#index' #render locations view - works
  get   '/about',           to: 'pages#about'
  resources :articles
  resources :photos, only: [:index]        # changed to resources :photos if not nesting
  #resources(:photos, {only: [:index]})
  #resources([:photos, {only: [:index]}])
  #get   '/photos',        to: 'photos#index' # change to 'get' if we want to nest route

  resources :locations do
    resources :photos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  #name is one of the unique columns in the locations table (see schema.rb)
  has_many :photos, dependent: :destroy

  validates :email, :password, uniqueness: true
  validates :email, :password, presence: true # make sure these fields are not empty

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name,
            presence: true,
            uniqueness: { case_sensitive: false}
  validates :longitude, presence: true
  validates :latitude, presence: true
end

#Location model is building off of ActiveRecord::Base
#Model connects to information(data) in the database to pull information route
#then will pass information to the Controller

#The validation happens by performing an SQL query into the model's table,
#searching for an existing record with the same value in that attribute.

#making a validation that requires the presence of an attribute is to help you make sure
  #that you are getting all of the data you need to make your app work.
    #Adding a uniqueness constraint helps to make sure users don't enter duplicate data.

#has_many :photos, dependent: :destroy
  #when a location is deleted, all of its photos are deleted too

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :location
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photos # photo may beleong to user who uploaded it
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
      @article = Article.new
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
  if @article.save
      flash[:notice] = "Article was successfully created"
    redirect_to article_path(@article)
  else
   render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
   end

   def edit
      @article = Article.find(params[:id])
   end

   def update
     @article = Article.find(params[:id])
     if @article.update(article_params)
      flash[:notice] = "Article was updated"
      redirect_to article_path(@article)
     else
      flash[:notice] = "Article was not updated"
      render 'edit'
     end
   end

  private
    def article_params
     params.require(:article).permit(:title, :description, :image_file)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home 
    @photo = Photo.all.shuffle.first
  end 
    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # from url locations/1
  def show
    @location = Location.find(params[:id])
  end

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end


#both Location.all is a model method defined by Rails
#find - only expects you to give it the 'ID' - only find by (params[:id])


private

  def location_params
    params.require(:location).permit(:latitude, :longitude, :city, :country,
                                      :visit_date, :state, :name, :description)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # url /photos/1
  def show
    @photo = Photo.find(params[:id]) 
  end

  def index
    @photos = Photo.all
  end

  def new
    @location = Location.find(params[:location_id]) #nested routes didn't work for line 12 & 13
    @photo = @location.photos.new # set up the association
    #@photo = Photo.new
  end

  def create
    @location = Location.find(params[:location_id])
    @photo = @location.photos.new(photo_params)
    if @photo.save
      redirect_to location_photos_path(@location), notice: "photo was added"
    else
      render :new
  end
end

private

  def photo_params
    params.require(:photo).permit(:name, :image_url, :caption)
  end
end


# "whitelist", or explicitly allow, paramters, we're using the methods require
  # and 'permit'. This means we 'require' the name of the array or hash to be in Params
  # (otherwise it'll throw an error), and then we 'permit' the individual attributes inside
  # the hash to be used. Only specified params will retun the hash. Otherwise, nothing will show up
  # if we didn't whitlist, when we try to access params[:post] nothing would show up!

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def image_source(photo)
    path = "https://placehold.it/300x300.png" if photo.blank? 
    path = photo.filepath.present? ? photo.filepath : photo.image_url
    image_tag(path)
  end

  
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from saving:</h2>
 <ul>
    <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
  <% end %>
 </ul>
<% end %>

<%= form_for @article do |f| %>
<p>
 <%= f.label :image_file %><br>
 <%= f.text_field :image_file %>
</p>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<table>
 <tr> image
  <th>Title</th>
  <th>Description</th>
 </tr>
 <% @articles.each do |article| %>
 <tr>
  <td><%= article.image_file %></td>
  <td><%= article.title %></td>
  <td><%= article.description %></td>
  <td><%= link_to 'Edit', edit_article_path(article) %></td>
  <td><%= link_to 'Show', article_path(article) %></td>
 </tr>
 <% end %>
</table>

app/views/articles/new.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from saving:</h2>
  <ul>
 <% @article.errors.full_messages.each do |msg|%>
  <li><%= msg %></li>
<% end %>
  </ul>
<% end %>


<h1>Create an article</h1>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
 </p>
 <p>
   <%= f.submit %>
 </p>

<% end %>

app/views/articles/show.html.erb
<h1>Show selected article</h1>

<h2>
 <%= @article.title %>
</h2>
  <%= image_tag "photos/#{@article.image_file}" %>

<p>
 Description: <%= @article.description %>
</p>

<p>
  <%= link_to "Edit", edit_article_path(@article) %>
</p>

<p>
  <%= render 'articles/form', article: @article %>
</p>

app/views/home/home.html.erb
<% provide(:title, "About") %>

<div class="text-center jumbotron">
  <h1> Welcome to Anna's Blog </h1>

<%= image_source(@photo) %>

</div>





 <footer><p>© <%= Date.today.year %> Created by Anna Nickle</p></footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>

  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <% flash.each do |name, msg| %>
        <ul>
         <li><%= msg %></li>
        </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<ul class='photo_list'>
  <li>
    <%= image_tag("/assets/photos/StarbucksReserveRoastery.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/CanyonlandsSunset.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/Bogota2.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/ChicagoMagMi.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/Harbin.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/MedellinFarmHouse.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/SF1.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/StLouis.jpg", :class=> "photo") %>
  </li>
  <li>
    <%= image_tag("/assets/photos/PittockMansionAcres.jpg", :class=> "photo") %>
  </li>
</ul>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Locations Traveled</h1>
<!--tr- new row in the table -->
<!-- th table header/lable for each column -->

<table>
 <tr>
  <th>Name</th>
  <th>Photo</th>
  <th>Description</th>
  <th>Longitude</th>
  <th>Latitude</th>
  <th>City</th>
  <th>State</th>
  <th>Country</th>
  <th>visit date</th>
  <th>Actions</th>
 </tr>

 <tbody>
 <% @locations.each do |location| %>
 <!-- using this method from controller- @locations = Location.all -
 to go through and render info for each location, thus @locations.each -->

  <!-- td - table data- info within the table -->
   <tr>
      <td><%= location.name %></td>
      <td><%= image_source(location.photos&.first) %></td>
      <td><%= location.description %></td>
      <td><%= location.longitude%></td>
      <td><%= location.latitude %></td>
      <td><%= location.city %></td>
      <td><%= location.state %></td>
      <td><%= location.country %></td>
      <td><%= location.visit_date %></td>
      <td><%= link_to 'Show', location_path(location) %></td>
    </tr>
 <% end %>
 </tbody>
</table>

app/views/locations/new.html.erb
<% provide(:title, 'New photo') %>
<h1>New Photo</h1>

app/views/locations/show.html.erb
<div>
  <strong>Location</strong>
  <%= @location.name %>
</div>

<div style="padding-left:80px;">
  <%= @location.description %>
</div>
<div style="padding-left:80px;">
 <%= @location.city %>, <%= @location.state %>,  <%= @location.country %>
</div>

<% @location.photos.each do |photo| %>   <!-- looping through each photo -->
  <%= image_source(photo) %>
<% end %>

<p>
  <%= link_to @location.name %>
</p>

app/views/pages/about.html.erb
<div class="p-20">
<div class="border border-l-8 border-blue-500 shadow round-lg p-10 mb-10">
About Me
</div>

<!-- button -->
  <button class="bg-blue-500 rounded-full py-2 px-8 shadow-lg text-green-100 hover:bg-blue-500"><%= link_to "Back", :back %></button>

</div>





<%#= link_to 'Home', root_path %>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <title>Google Maps</title>
  </head>

  <body>
      <h1>Contact</h1>

      <p>
            <strong>Address:</strong>
            <br>123 Main Street>
            <br>Columbus, OH 43215
      </p>

      <p>
            <strong>Phone: (800) 123 4567
      </p>

      <p><iframe src="https://www.google.com/maps/embed?
        pb=!1m14!1m8!1m3!1d782628.1331622847!2d-82.990829!3d39.982951!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x883889c1b990de71%3A0xe43266f8cfb1b533!2sColumbus%2C%20OH!5e0!3m2!1sen!2sus!4v1575380899767!5m2!1sen!2sus" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe></p>

    </body>
</html>

#https://www.youtube.com/watch?v=KIC0OK9nKXY

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>

<%= link_to 'About', about_path %>

app/views/photos/new.html.erb
<% provide(:title, 'New photo') %>
<h1>New photo</h1>

<%= form_for([@location, @photo]) do |f| %>
  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>
  <div>
    <%= f.submit %>
    <%= link_to "Cancel", @location, class: 'button' %> <!-- link to location show page -->
  </div>
<% end %>

app/views/photos/show.html.erb
<% provide(:title, 'Photo') %>
<!-- showing individual photo -->
<p>
  <strong>Photo</strong>
</p>

<%= image_tag("https://images.unsplash.com/photo-1452784444945-3f422708fe5e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1952&q=80", {:style => "width:100px;"}) %>

app/views/shared/_navbar.html.erb
<nav> 
  <ul>
    <li>
      <%= link_to("Home", root_path) %>
    </li>
    <li>
      <!-- link -->
      <%= link_to("About", about_path) %>
    </li>
    <li>
      <!-- link -->
      <%= link_to("Locations", locations_path) %>
    </li>
    <li>
      <!-- link -->
      <%= link_to("Photos", photos_path) %>
    </li>
    <li>
    <!-- link -->
    <!-- <a href="/">Home</a> -->
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to("Log in", new_user_session_path) %>
      <% end %>
    </li>
  </ul>
</nav>